spring:
  datasource:
    url: jdbc:hsqldb:file:eventsdb
    username: sa
    password: sa
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate:
      ddl-auto: create

application:
  alert-trigger: 4000